version: '3'

services:
  db:
    image: postgres:15
    container_name: postgres_workout
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workout
    ports:
      - "5433:5432"
  
  